
function [sub_segment_points, ...
          sub_segment_points_transformed, ...
          sub_segment_points_abcd_values] = recalc_stored_data(start_points, end_points, ...
                                                               t_n, step_size, segment_splits, ...
                                                               sub_segment_points, ...
                                                               sub_segment_points_transformed, ...
                                                               sub_segment_points_abcd_values)

    for t_i = 1:t_n
        curr_segment = GeodesicSegment(start_points(t_i), end_points(t_i));
        [sub_segment_points, ...
         sub_segment_points_transformed, ...
         sub_segment_points_abcd_values] = store_new_segment_data(t_i, curr_segment, ...
                                                                  step_size, segment_splits, ...
                                                                  sub_segment_points, ...
                                                                  sub_segment_points_transformed, ...
                                                                  sub_segment_points_abcd_values);
    end
end